import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Award, Bookmark, Camera, CakeSlice, Check, Clock, Share2, Sparkles, Star } from "lucide-react";
import { AppHeader, Badge, images } from "@/components/atelier";
import { Button } from "@/components/ui/button";
import type { LucideIcon } from "lucide-react";

export const Route = createFileRoute("/conclusao")({ head: () => ({ meta: [{ title: "Receita Concluída — Velvet Atelier" }, { name: "description", content: "Sua obra-prima de confeitaria está pronta." }, { property: "og:title", content: "Receita Concluída — Velvet Atelier" }, { property: "og:description", content: "Sua obra-prima de confeitaria está pronta." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Completion });

const summary: Array<{ icon: LucideIcon; label: string; value: string }> = [
  { icon: Clock, label: "Tempo gasto", value: "48 min" },
  { icon: CakeSlice, label: "Rendimento", value: "4 fatias" },
  { icon: Award, label: "Nível técnico", value: "Avançado" },
  { icon: Check, label: "Execução", value: "5 de 5" },
];

function Completion() {
  const [rating, setRating] = useState(5); const [saved, setSaved] = useState(false); const [notes, setNotes] = useState(["Leve & Aveludado", "Picos Perfeitos"]);
  const toggle = (note: string) => setNotes((all) => all.includes(note) ? all.filter((item) => item !== note) : [...all, note]);
  return <div className="min-h-screen pb-10"><AppHeader title="Receita Concluída" back /><main className="mx-auto max-w-4xl px-4 py-5 sm:px-6"><section className="text-center"><Badge><Sparkles className="size-3.5" /> Receita concluída com sucesso</Badge><h1 className="mt-3 font-display text-4xl font-semibold">Parabéns, Chef!</h1><p className="mt-2 font-display text-xl italic text-primary">Sua obra-prima está pronta.</p><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Você completou todas as 5 etapas com maestria e precisão.</p></section>
    <div className="mt-6 grid gap-5 md:grid-cols-[1.2fr_1fr]"><div className="space-y-5"><div className="relative aspect-[4/3] overflow-hidden rounded-lg shadow-card"><img src={images.finished} alt="Bolo chiffon finalizado" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-image-scrim" /><span className="absolute left-3 top-3"><Badge><Award className="size-3.5" /> Obra de arte finalizada</Badge></span><div className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-2 text-inverse-foreground"><div><span className="text-[10px] font-bold uppercase">Haute Pâtisserie</span><h2 className="font-display text-xl font-semibold">Chiffon de Framboesa & Baunilha</h2></div><Button variant="white" size="sm"><Camera className="size-4" /> Minha foto</Button></div></div>
      <section className="rounded-lg bg-card p-4 shadow-card"><div className="flex items-center justify-between"><h2 className="font-bold">Resumo da Sessão Gourmet</h2><Badge>Perfeição 100%</Badge></div><div className="mt-3 grid grid-cols-2 gap-2">{summary.map(({ icon: Icon, label, value }) => <div key={label} className="rounded-lg bg-secondary p-3"><Icon className="size-4 text-primary" /><span className="mt-2 block text-[10px] font-bold uppercase text-muted-foreground">{label}</span><strong className="font-display text-lg">{value}</strong></div>)}</div></section></div>
      <div className="space-y-5"><section className="rounded-lg bg-card p-5 text-center shadow-card"><h2 className="font-display text-xl font-semibold">Como ficou sua criação?</h2><p className="mt-1 text-xs text-muted-foreground">Avalie a textura e a harmonia</p><div className="my-4 flex justify-center gap-1">{[1,2,3,4,5].map((value) => <Button key={value} aria-label={`${value} estrelas`} variant="ghost" size="icon" onClick={() => setRating(value)}><Star className={`size-7 text-primary ${value <= rating ? "fill-current" : ""}`} /></Button>)}</div><p className="mb-3 text-xs font-bold">Notas de degustação pessoal</p><div className="flex flex-wrap justify-center gap-2">{["Leve & Aveludado", "Doçura Equilibrada", "Picos Perfeitos", "Aroma Marcante", "Frutas Frescas"].map((note) => <Button key={note} size="sm" variant={notes.includes(note) ? "primary" : "soft"} onClick={() => toggle(note)}>{note}</Button>)}</div><blockquote className="mt-5 rounded-lg bg-secondary p-4 font-display italic text-muted-foreground">“A confeitaria é a fusão perfeita entre a precisão matemática e a paixão dos sentidos.”</blockquote></section>
      <div className="space-y-3"><Button className="w-full" onClick={() => navigator.share?.({ title: "Velvet Atelier", text: "Minha obra-prima está pronta!" })}><Share2 className="size-4" /> Compartilhar conquista & foto</Button><Button variant="soft" className="w-full" onClick={() => setSaved(true)}>{saved ? <Check className="size-4" /> : <Bookmark className="size-4" />}{saved ? "Guardado no Caderno" : "Salvar no Meu Caderno"}</Button><Button asChild variant="ghost" className="w-full"><Link to="/">Voltar ao Caderno Gourmet</Link></Button></div></div></div>
  </main></div>;
}