import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ChefHat, Lightbulb, Pause, Play, RotateCcw, ShoppingBasket, Sun, Volume2 } from "lucide-react";
import { AppHeader, Badge, images } from "@/components/atelier";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/cozinha")({ head: () => ({ meta: [{ title: "Modo Cozinha — Velvet Atelier" }, { name: "description", content: "Guia passo a passo para seu bolo chiffon." }, { property: "og:title", content: "Modo Cozinha — Velvet Atelier" }, { property: "og:description", content: "Guia passo a passo para seu bolo chiffon." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Kitchen });

function Kitchen() {
  const [seconds, setSeconds] = useState(480); const [running, setRunning] = useState(false);
  useEffect(() => { if (!running || seconds <= 0) return; const id = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(id); }, [running, seconds]);
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="min-h-screen pb-24"><AppHeader title="Modo Cozinha" back /><main className="mx-auto max-w-4xl px-4 py-4 sm:px-6">
    <div className="flex items-center justify-between"><Badge><Sun className="size-3.5" /> Tela ativa</Badge><Button asChild variant="soft" size="sm"><Link to="/">Sair do modo cozinha</Link></Button></div>
    <section className="mt-4 rounded-lg bg-card p-4 shadow-card"><div className="flex items-center justify-between text-xs font-bold"><span className="uppercase text-muted-foreground">Progresso da execução</span><span className="text-primary">Passo 02 de 05 · 40%</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-muted"><div className="h-full w-2/5 rounded-full bg-primary" /></div></section>
    <div className="mt-4 grid gap-4 md:grid-cols-[1fr_320px]"><div className="space-y-4"><div className="relative h-52 overflow-hidden rounded-lg"><img src={images.meringue} alt="Merengue francês em uma tigela" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-image-scrim" /><span className="absolute bottom-4 left-4 rounded-full bg-card/90 px-3 py-1 text-xs font-bold text-primary">Bolo Chiffon de Framboesa & Baunilha</span></div>
      <section className="rounded-lg bg-card p-5 shadow-card"><div className="flex items-center gap-2 text-primary"><ChefHat className="size-5" /><span className="text-[10px] font-bold uppercase">Técnica de confeitaria</span></div><h1 className="mt-3 font-display text-3xl font-semibold">02. Aeração do Merengue Francês</h1><p className="mt-3 text-base leading-7 text-muted-foreground">Bata as claras em velocidade média até espumarem. Adicione um terço do açúcar gradualmente e continue batendo até obter picos firmes, brilhantes e sedosos.</p><div className="mt-4 flex gap-3 rounded-lg bg-secondary p-4"><Lightbulb className="size-5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground"><strong className="block text-primary">Dica de Ouro do Chef</strong>A tigela e os batedores devem estar 100% livres de gordura e umidade.</p></div></section>
      <section className="rounded-lg bg-card p-4 shadow-card"><h2 className="flex items-center gap-2 font-bold"><ShoppingBasket className="size-5 text-primary" /> Ingredientes para esta etapa</h2>{[["Claras de ovos orgânicos", "4 un"], ["Açúcar refinado ou impalpável", "40g"]].map(([name, qty], index) => <div key={name} className="mt-2 flex items-center justify-between rounded-lg bg-secondary p-3 text-sm"><span><b className="mr-2 text-primary">{index + 1}</b>{name}</span><strong className="rounded-full bg-card px-3 py-1 text-primary">{qty}</strong></div>)}</section>
    </div><aside className="rounded-lg bg-card p-5 text-center shadow-card md:sticky md:top-20 md:self-start"><div className="flex justify-between text-[10px] font-bold uppercase text-muted-foreground"><span>Cronômetro</span><Volume2 className="size-4 text-primary" /></div><div className="relative mx-auto my-6 flex size-56 items-center justify-center rounded-full border-[10px] border-secondary"><div><div className="font-display text-5xl font-semibold">{time}</div><p className="mt-2 text-xs font-bold text-primary">{running ? "Batendo merengue..." : "Pausado"}</p></div></div><Button className="w-full" onClick={() => setRunning((value) => !value)}>{running ? <Pause className="size-5" /> : <Play className="size-5 fill-current" />}{running ? "Pausar cronômetro" : "Iniciar cronômetro"}</Button><div className="mt-3 flex gap-2"><Button variant="soft" size="sm" className="flex-1" onClick={() => setSeconds((v) => v + 60)}>+1 min</Button><Button variant="soft" size="sm" className="flex-1" onClick={() => setSeconds((v) => v + 30)}>+30 seg</Button><Button aria-label="Reiniciar" variant="soft" size="icon" className="size-9" onClick={() => { setRunning(false); setSeconds(480); }}><RotateCcw className="size-4" /></Button></div></aside></div>
  </main><div className="fixed inset-x-0 bottom-0 z-30 border-t bg-background/92 p-3 backdrop-blur"><div className="mx-auto flex max-w-md gap-3"><Button variant="soft" className="flex-1">Anterior</Button><Button asChild className="flex-[2]"><Link to="/conclusao">Concluir & avançar</Link></Button></div></div></div>;
}