/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as ConclusaoRouteImport } from './routes/conclusao'
import { Route as CozinhaRouteImport } from './routes/cozinha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusaoRoute = ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/conclusao': typeof ConclusaoRoute
  '/cozinha': typeof CozinhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/conclusao': typeof ConclusaoRoute
  '/cozinha': typeof CozinhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/conclusao': typeof ConclusaoRoute
  '/cozinha': typeof CozinhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecao' | '/conclusao' | '/cozinha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecao' | '/conclusao' | '/cozinha'
  id: '__root__' | '/' | '/colecao' | '/conclusao' | '/cozinha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecaoRoute: typeof ColecaoRoute
  ConclusaoRoute: typeof ConclusaoRoute
  CozinhaRoute: typeof CozinhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusao': {
      id: '/conclusao'
      path: '/conclusao'
      fullPath: '/conclusao'
      preLoaderRoute: typeof ConclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecaoRoute: ColecaoRoute,
  ConclusaoRoute: ConclusaoRoute,
  CozinhaRoute: CozinhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
